### ISSUE TITLE
Outline: handle lists within lists

### ISSUE THREAD

**Issue by andreoliwa** [andreoliwa/logseq-doctor#2]
## Expected behavior

Lists within lists should have their hierarchy respected when converted to an outline.

This:

```markdown
# Header

- Parent
  - Child 1
  - Child 2
```

Should be converted to:

```markdown
- # Header
  - Parent
    - Child 1
    - Child 2
```

## Current behavior

This is the current output of the `outline` command:

```markdown
- # Header
  - Parent
  - Child 1
  - Child 2
```

## Steps to reproduce

1. Run `poetry run lsd outline path/to/file.md` with the contents above.

## Possible Solution

?

**Comment by huyz** [comment]
Yes, nested lists are very common. Are there workarounds?

**Comment by andreoliwa** [comment]
Not yet. I didn't check the Markdown parser to see how nested lists are handled.

**Comment by huyz** [comment]
I'm checking out what pandoc can do. If not, I'll be back ;)
