### ISSUE TITLE
Can't even do lsd --help

### ISSUE THREAD

**Issue by jajpater** [andreoliwa/logseq-doctor#39]
## Expected behavior

Give an overview of options

## Current behavior

Error message

## Steps to reproduce

type `lsd --help`

Then I get this error:

`Traceback (most recent call last):
  File "/home/jajpater/.local/bin/lsd", line 5, in <module>
    from logseq_doctor.cli import main
  File "/home/jajpater/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/logseq_doctor/__init__.py", line 1, in <module>
    from mistletoe import BaseRenderer
ImportError: cannot import name 'BaseRenderer' from 'mistletoe' (/home/jajpater/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/__init__.py)`

- `logseq-doctor` version used: installed by pipx
- Python version: 3.10
- Operating System and version: Ubuntu 22.04
- Run the following commands and paste the output:

  ```shell script
  which python3
  python3 -V
  pip freeze
  cat $(which flake8)
  ```
/usr/bin/python3

Pythone 3.10.4

age==0.4.1
ansible-base==2.10.8
apache-libcloud==3.2.0
APScheduler==3.6.3
apturl==0.5.2
argcomplete==2.0.0
asciinema==2.1.0
Babel==2.8.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
blinker==1.4
Brlapi==0.8.3
cachetools==4.2.2
certifi==2020.6.20
cffi==1.15.1
chardet==4.0.0
click==7.1.2
colorama==0.4.4
coloredlogs==7.3
command-not-found==0.3
cryptography==3.4.8
css-parser==1.0.7
cssselect==1.1.0
cssutils==1.0.2
csv-ical==2.0.4
csv2md==1.1.2
cupshelpers==1.0
Cython==0.29.28
dataclasses==0.6
dataclasses-json==0.5.7
dbus-python==1.2.18
decorator==4.4.2
defer==1.0.6
defusedxml==0.7.1
Deprecated==1.2.13
distlib==0.3.4
distro==1.7.0
distro-info===1.1build1
dnspython==2.1.0
docopt==0.6.2
dulwich==0.20.31
duplicity==0.8.21
evdev==1.4.0
fasteners==0.14.1
fastimport==0.9.14
filelock==3.6.0
Flask==2.0.1
folder-color==0.0.86
folder-color-common==0.0.86
future==0.18.2
html5lib==1.1
httplib2==0.20.2
humanfriendly==10.0
i3ipc==2.2.1
icalendar==4.1.0
idna==3.3
ifaddr==0.1.7
img2pdf==0.4.2
importlib-metadata==4.6.4
itsdangerous==2.1.0
jeepney==0.7.1
Jinja2==3.0.3
jmespath==0.10.0
keyring==23.5.0
krop==0.6.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lockfile==0.12.2
louis==3.20.0
lxml==4.8.0
macaroonbakery==1.3.1
Mako==1.1.3
marc2bib==0.1.6
MarkupSafe==2.0.1
marshmallow==3.17.0
marshmallow-enum==1.5.1
mistletoe==0.9.0
mkchromecast==0.3.9
monotonic==1.6
more-itertools==8.10.0
mypy-extensions==0.4.3
netaddr==0.8.0
netifaces==0.11.0
nose==1.3.7
notify2==0.3
ntlm-auth==1.4.0
numpy==1.21.5
oauthlib==3.2.0
ocrmypdf==13.4.0+dfsg
odfpy==1.4.2
olefile==0.46
packaging==21.3
pandas==1.4.3
paramiko==2.9.3
pdfminer.six===-VERSION-
pexpect==4.8.0
pikepdf==5.0.1+dfsg
Pillow==9.0.1
pipsi==0.9
pipx==1.1.0
platformdirs==2.5.1
pluggy==0.13.0
prettytable==2.5.0
prompt-toolkit==3.0.30
protobuf==3.12.4
psutil==5.9.0
ptyprocess==0.7.0
pulseaudio-dlna==0.6.0
pycairo==1.20.1
PyChromecast==9.4.0
pycparser==2.21
pycryptodome==3.15.0
pycryptodomex==3.11.0
pycups==2.0.1
pyenchant==3.2.0
PyGithub==1.55
PyGObject==3.42.1
pyinotify==0.9.6
PyJWT==2.3.0
pykerberos==1.1.14
pymacaroons==0.13.0
pymarc==4.2.0
PyNaCl==1.5.0
pyOpenSSL==21.0.0
pypandoc==1.8.1
pyparsing==2.4.7
PyPDF2==1.26.0
pyperclip==1.8.2
PyQt5==5.15.6
PyQt5-sip==12.9.1
pyRFC3339==1.1
pyroute2==0.post0
pyroute2.core==0.post0
pyroute2.ethtool==0.post0
pyroute2.ipdb==0.post0
pyroute2.ipset==0.post0
pyroute2.ndb==0.post0
pyroute2.nftables==0.post0
pyroute2.nslink==0.post0
pyroute2.protocols==0.post0
pyte==0.8.0
python-apt==2.3.0+ubuntu2.1
python-dateutil==2.8.1
python-debian===0.1.43ubuntu1
python-distutils-extra==2.39
python-poppler-qt5==0.75.0
python-sane==2.9.1
python-telegram-bot==13.13
python-xlib==0.29
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
pyudev==0.23.2
pywinrm==0.3.0
pyxattr==0.7.2
pyxdg==0.27
PyYAML==5.4.1
ranger-fm==1.9.3
regex==2021.11.10
reportlab==3.6.8
requests==2.25.1
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rofication==1.2.2
scour==0.38.2
SecretStorage==3.3.1
selinux==3.3
setproctitle==1.2.2
simplejson==3.17.6
six==1.16.0
solaar==1.1.4
soupsieve==2.3.1
speedtest-cli==2.1.3
systemd-python==234
tabulate==0.8.10
thefuck==3.32
tornado==6.2
tqdm==4.57.0
typing-inspect==0.7.1
typing_extensions==4.3.0
tzdata==2022.1
tzlocal==4.2
ubuntu-advantage-tools==27.9
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
usb-creator==0.3.7
userpath==1.8.0
virtualenv==20.13.0+ds
wadllib==1.3.6
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.2
wrapt==1.14.1
xdg==5
xkit==0.0.0
xmltodict==0.12.0
youtube-dl==2021.12.17
zeroconf==0.38.3
zipp==1.0.0

`#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'flake8==4.0.1','console_scripts','flake8'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'flake8==4.0.1'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point

def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()

globals().setdefault('load_entry_point', importlib_load_entry_point)

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('flake8==4.0.1', 'console_scripts', 'flake8')())`

**Comment by andreoliwa** [comment]
Thanks for the bug report!
The new version should fix this: https://pypi.org/project/logseq-doctor/0.1.1/

If not, please write here again and I'll take a look.
